FROM golang:1.18.3-alpine

ENV GO111MODULE=on
WORKDIR /go/src/github.com/inpulse-tv/docker-optimisation/

RUN apk update && \
    apk add ca-certificates

COPY go.mod ./
COPY go.sum ./
COPY main.go ./

RUN go mod download && \
    go build -o app main.go

CMD [ "./app" ]