FROM golang:1.18.3

ENV GO111MODULE=on
WORKDIR /go/src/github.com/inpulse-tv/docker-optimisation/

COPY go.mod ./
COPY go.sum ./
COPY main.go ./

RUN apt-get update
RUN apt-get install ca-certificates

RUN go mod download
RUN go build -o app main.go

CMD [ "./app" ]