FROM golang:1.18.3-alpine

ENV GO111MODULE=on
WORKDIR /go/src/github.com/inpulse-tv/docker-optimisation/

COPY go.mod ./
COPY go.sum ./
COPY main.go ./

RUN apk update
RUN apk add ca-certificates

RUN go mod download
RUN go build -o app main.go

CMD [ "./app" ]